# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Map step outputs to a job outputs
    outputs:
      VER: ${{ steps.vars.outputs.VER }}
      REL: ${{ steps.vars.outputs.REL }}
      DATE: ${{ steps.vars.outputs.DATE }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # output
      - name: Run a one-line script
        id: vars
        run: |
          echo ::set-output name=VER::$(sh ./next_ver.sh)
          echo ::set-output name=REL::$(python ./rel.py)
          echo ::set-output name=DATE::$(date "+%x")

  windows-latest:
    needs: [init]
    runs-on: windows-latest
    steps:
      - name: echo
        run: |
          echo VER=${{ needs.init.outputs.VER }}
          echo REL=${{ needs.init.outputs.REL }}
          echo DATE=${{ needs.init.outputs.DATE }}

  ubuntu-latest:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo VER=${{ needs.init.outputs.VER }}
          echo REL=${{ needs.init.outputs.REL }}
          echo DATE=${{ needs.init.outputs.DATE }}
