# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Map step outputs to a job outputs
    outputs:
      VER: ${{ steps.vars.outputs.VER }}
      REL: ${{ steps.vars.outputs.REL }}
      DATE: ${{ steps.vars.outputs.DATE }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # output
      - name: Run a one-line script
        id: vars
        run: |
          VER=$(cat phreeqc-version.txt)
          ver_major=$(echo "$VER" | awk -F. '{print $1}')
          ver_minor=$(echo "$VER" | awk -F. '{print $2}') 
          if [ -z "$ver_minor" ]; then
            ver_minor=0
            ver_patch=0
          else
            ver_patch=$(echo "$VER" | awk -F. '{print $3}')
            if [ -z "$ver_patch" ]; then
              ver_patch=0
            else
              ver_patch=$((ver_patch+1))    
            fi
          fi          
          echo ::set-output name=VER::${ver_major}.${ver_minor}.${ver_patch}
          echo ::set-output name=REL::$(python ver.py)
          echo ::set-output name=DATE::$(date "+%x")

  build:
    needs: init
    runs-on: windows-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo VER=${{ needs.init.outputs.VER }}
          echo REL=${{ needs.init.outputs.REL }}
          echo DATE=${{ needs.init.outputs.DATE }}
